sources:
- name: "Canny Edge Detection (Python)"
  url: "https://docs.opencv.org/4.x/da/d22/tutorial_py_canny.html"
- name: "Contours: Getting Started (Python)"
  url: "https://docs.opencv.org/4.x/d4/d73/tutorial_py_contours_begin.html" 
- name: "Contours TOC (Python)"
  url: "https://docs.opencv.org/4.x/d3/d05/tutorial_py_table_of_contents_contours.html"
- name: "Feature Matching (Python)"
  url: "https://docs.opencv.org/4.x/dc/dc3/tutorial_py_matcher.html"
- name: "Feature Matching + Homography (Python)"
  url: "https://docs.opencv.org/4.x/d1/de0/tutorial_py_feature_homography.html"
- name: "Camera Calibration (Python)"
  url: "https://docs.opencv.org/4.x/dc/dbb/tutorial_py_calibration.html"
- name: "Image Processing TOC (Python)"
  url: "https://docs.opencv.org/4.x/d2/d96/tutorial_py_table_of_contents_imgproc.html" 